sudo: false
dist: focal
language: java
before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 17-open
  - sdk use java 17-open
  - sdk install maven
cache:
  directories:
    - '$HOME/.m2/repository'
